### ISSUE TITLE
rollup-plugin-babel incompatible with node 13

### ISSUE THREAD

**Issue by kevinramharak** [gojutin/typescript-playground-plugin-react#5]
`rollup-plugin-babel` throws a build error:

```
src/index.tsx → dist/index.js...
[!] (plugin babel) Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- C:\Users\Kevin\Projects\playground-file-explorer-browser-fs\node_modules\@babel\preset-env\lib\polyfills\corejs3\usage-plugin.js
- C:\Users\Kevin\Projects\playground-file-explorer-browser-fs\node_modules\@babel\preset-env\lib\index.js
- C:\Users\Kevin\Projects\playground-file-explorer-browser-fs\node_modules\@babel\core\lib\config\files\plugins.js
- C:\Users\Kevin\Projects\playground-file-explorer-browser-fs\node_modules\@babel\core\lib\config\files\index.js
- C:\Users\Kevin\Projects\playground-file-explorer-browser-fs\node_modules\@babel\core\lib\index.js
- C:\Users\Kevin\Projects\playground-file-explorer-browser-fs\node_modules\rollup-plugin-babel\dist\rollup-plugin-babel.cjs.js
- C:\Users\Kevin\Projects\playground-file-explorer-browser-fs\rollup.config.js
- C:\Users\Kevin\Projects\playground-file-explorer-browser-fs\node_modules\rollup\dist\bin\rollup
src\index.tsx
Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- C:\Users\Kevin\Projects\playground-file-explorer-browser-fs\node_modules\@babel\preset-env\lib\polyfills\corejs3\usage-plugin.js
- C:\Users\Kevin\Projects\playground-file-explorer-browser-fs\node_modules\@babel\preset-env\lib\index.js
- C:\Users\Kevin\Projects\playground-file-explorer-browser-fs\node_modules\@babel\core\lib\config\files\plugins.js
- C:\Users\Kevin\Projects\playground-file-explorer-browser-fs\node_modules\@babel\core\lib\config\files\index.js
- C:\Users\Kevin\Projects\playground-file-explorer-browser-fs\node_modules\@babel\core\lib\index.js
- C:\Users\Kevin\Projects\playground-file-explorer-browser-fs\node_modules\rollup-plugin-babel\dist\rollup-plugin-babel.cjs.js
- C:\Users\Kevin\Projects\playground-file-explorer-browser-fs\rollup.config.js
- C:\Users\Kevin\Projects\playground-file-explorer-browser-fs\node_modules\rollup\dist\bin\rollup
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (C:\Users\Kevin\Projects\playground-file-explorer-browser-fs\node_modules\@babel\preset-env\lib\polyfills\corejs3\usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
```

Proposed fix: https://github.com/nodejs/node/issues/32852

**Comment by just214** [comment]
I just pushed an update with updated dependencies. Hopefully this resolves the issue. If not, please feel free to reopen.
